### ISSUE TITLE
Chash attached files

### ISSUE THREAD

**Issue by dmitrygribenchuk** [kepi/show-gravatar#13]
Hey! When I enable this plugin some attaches chash, when I swith off the plugin  - all ok.

**Comment by kepi** [comment]
Hey @dmitrygribenchuk can you please be more specific? Which version of roundcube are you using? Do you have specific message which is causing trouble? Log messages? Thansk

**Comment by dmitrygribenchuk** [comment]
I'm use roundcube version 1.2.1 and 1.2.3 with postgresql and mysql database.
When I open attachment (image) I see error (text):

The image 'http://mydomain.net/?_task=mail&action=get&_mbox=INBOX&_uid=2012&_part=2&extwin=1&_mimewarning=1&_embed=1" cannot be displayed because it contains errors.

In logs of roundcube (sql, ldap, imap) no anything about error (I have the biggest log level in config).

**Comment by kepi** [comment]
Do you have specific attachments which are always crashing? It would be great to be able to reproduce it in my environment.

I tried with multiple attachments in 1.2.3 without triggering this bug.

**Comment by dmitrygribenchuk** [comment]
In attachment I have regular files (jpg, pdf, etc).

My enviroment: 
Debian jessie, postgresql 9.4.10, nginx 1.10.2, php5-fpm 5.6.29, roundcube 1.2.3-complete.
Enabled pluggins: 'archive', 'zipdownload', 'show_gravatar', 'mobile'

**Comment by kepi** [comment]
Please send me couple problematic messages to my test mail (i just sent you mail from it).

environment is almost same so still not sure what can be problem.

one more piece - what browser are you using?

**Comment by dmitrygribenchuk** [comment]
I sent it.

**Comment by dmitrygribenchuk** [comment]
I'm using firefox and google chome (all time last stable version)

**Comment by kepi** [comment]
Thanks, received. "Unfortunately" it is working without any problem.

Can you please try one more thing - disable all plugins but show_gravatar, if it helps? I suppose not but only to be sure. I'll try to investigate more but it will take me some time.

**Comment by dmitrygribenchuk** [comment]
Look. I disabled all plugins - attachment ok. I enable your plugin - problem return

**Comment by dmitrygribenchuk** [comment]
I can show it to you via teamviewer for example

**Comment by kepi** [comment]
@dmitrygribenchuk I'm sorry but I didn't get notification those two years back and didn't found you replied until now. Is the problem resolved or still present? Or you don't use the plugin anymore?

**Comment by kepi** [comment]
I rework multiple places when this problem could appear and removed all obsolete functionality. It should work now without any problem. Closing this now, feel free to re-open if you hit the issue with latest version again.
