### ISSUE TITLE
PHP Fatal Error: Call to undefined function Q()

### ISSUE THREAD

**Issue by balleyne** [kepi/show-gravatar#14]
I was getting a PHP fatal error when trying to access Roundcube settings in recent versions of Roundcube. Finally traced it to an outdated call to `Q()` in this plugin, which according to [this thread](https://github.com/priyadi/roundcube-converse.js-xmpp-plugin/issues/57) I realized should now be `rcube::Q()`.

Here's a patch that worked for me:
https://gist.github.com/balleyne/5be6ef0e2c7c690301eb717a13fe1f75

**Comment by kepi** [comment]
Thanks for your report and for finding the cause. I hit the error couple months ago but have no time, your issue pushed me to resolve this now :)

I found couple more troubles with recent RC versions so I fixed them all. Everything should work fine now, at least it is working fine now in our setup.

**Comment by balleyne** [comment]
Thanks for the fixes! I'd hit this a few months back too, finally had a chance to troubleshoot it. Thanks for the plugin!
