### ISSUE TITLE
Get gravatar from somewhere else

### ISSUE THREAD

**Issue by dresende** [kepi/show-gravatar#6]
It would be greate to return the gravatar from another place (like a private company avatar/photo location).

**Comment by mckaygerhard** [comment]
hi, i take it and review this plugin, its very usefully for company if could make available this feaure

use roundcube for own purposes are not so good, gmail services are more cheap

so that's why company focused target its the main, and this feature are very great if can be do!

**Comment by mckaygerhard** [comment]
i research the code on plugins, seems there{s a regular xpre for get images from gravatar, we can added and option to provide custom url for gravatars images and take it from a http server with profiles of the users!

**i mean someting like global constacts list shared via webdav!**

**Comment by prodrigestivill** [comment]
For companies one should configure and LDAP addressbook and there you can put all pictures.

If you still are willing to implement you own API, you can use [prodrigestivill/gravatar](https://github.com/prodrigestivill/roundcube-gravatar) in _config.inc.php_ you can define your own API or filesystem (check README.md).

**Comment by mckaygerhard** [comment]
thanks for the info... i'll check and report feedback here, great plugin

**Comment by kepi** [comment]
I will leave this function to other plugins, I want to keep this one really simple with only one task, showing gravatars. Feel free to leave here instructions for others who will need similar functionality, if i.e. [prodrigestivill/gravatar](https://github.com/prodrigestivill/roundcube-gravatar)can help with the task.

**Comment by mckaygerhard** [comment]
u have right, and thanks for the info, its that i have need it!
